### ISSUE TITLE
你好，请问可以公开你们的数据吗

### ISSUE THREAD

**Issue by gengyun1027** [AmberHen/WHU-OPT-SAR-dataset#1]

**Comment by AmberHen** [comment]
会的 请期待




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmberHen/WHU-OPT-SAR-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月10日(星期天) 晚上6:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[AmberHen/WHU-OPT-SAR-dataset] 你好，请问可以公开你们的数据吗 (#1)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AmberHen** [comment]
你好，已公开，欢迎使用！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmberHen/WHU-OPT-SAR-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月10日(星期天) 晚上6:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[AmberHen/WHU-OPT-SAR-dataset] 你好，请问可以公开你们的数据吗 (#1)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AmberHen** [comment]
We have updated the result image of the data prediction to the web disk.
